version: "3.7"
services:
    wildduck:
        container_name: wildduck
        restart: always
        build: .
        ports:
            - "8080:8080"
            - "143:143"
            - "110:110"
            - "993:993"
            - "995:995"
        depends_on:
            - redis
            - mongo
        volumes:
            - ./data/dbs.toml:/wildduck/config/dbs.toml
            - ./data/api.toml:/wildduck/config/api.toml
        environment:
            CMD_ARGS: "--dbs.mongo=mongodb://mongo:27017/ --dbs.redis=redis://redis:6379/3 --api.host=0.0.0.0"
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - /data
    mongo:
        image: mongo
        restart: always
        volumes:
            - /data/db