version: "3.7"
services:
    wildduck:
        container_name: wildduck
        restart: always
        build: .
        ports:
            - "8080:8080"
            - "143:143"
            - "110:110"
            - "993:993"
            - "995:995"
        depends_on:
            - cache
            - mongo
        volumes:
            - ./data/dbs.toml:/wildduck/config/dbs.toml
            - ./data/api.toml:/wildduck/config/api.toml
    redis:
        image: redis:alpine
        volumes:
            - /data
    mongo:
        image: mongo
        restart: always
        volumes:
            - /data/db